### ISSUE TITLE
My Mod Suggestions

### ISSUE THREAD

**Issue by Laqota** [intergrav/deckcraft#1]
[VulkanMod](https://modrinth.com/mod/vulkanmod) - Thought it would work good since Linux smashes through Vulkan
[Ksyxis](https://modrinth.com/mod/ksyxis) - Works well.
[Too Many Players](https://modrinth.com/mod/tmp) - Great for Large Multiplayer servers such as Hypixel.
[Simple Voice Chat](https://modrinth.com/plugin/simple-voice-chat) - Great for multiplayer and singleplayer.
[Voice Chat Interaction](https://modrinth.com/mod/voice-chat-interaction) - Great for SVC and makes Ancient city a quiet time Nightmare. Good for kids if your a parent, I guess.
[Immersive Portal Gun](https://modrinth.com/mod/portal-gun) - Now your question might be why. My answer is why not. You're playing Minecraft on the Steam Deck so why not put a Portal reference in game.
[Sound Physics Remastered](https://modrinth.com/mod/sound-physics-remastered) - Makes the game sound so much better and is compatible with SVC.

I don't own a steam deck (Yet) since It's coming tomorrow. I'll lyk if any of the mods I suggested work.

**Comment by intergrav** [comment]
1. VulkanMod doesn't have great compatibility with other mods, including Iris, which is very popular. It is in quite a work-in-progress state and can have bugs too
2. Fastload already implements what Ksyxis does
3. While it's a nice mod, it has quite a specific use case that most players won't need
4. Not every server supports the mod, and if it's needed, it should be added by the user. If it was included in the modpack, it could also become out of date over time and become incompatible with the server version
5. This is a server-side mod, and it does not function on the client
6. Not in the scope of this pack:
  a. This pack aims to leave vanilla unchanged and not add any in-game content. I do think it's a fun reference though :)
  b. The mod requires Immersive Portals, which is known to have incompatibilities with other mods, including mods that are already present in the pack. The behavior that Immersive Portals implements is also not in scope and can greatly impact performance
7. Same reason as 6a

I do appreciate the suggestions though.
