### ISSUE TITLE
Update to 1.20.4

### ISSUE THREAD

**Issue by ARE2KUSU** [intergrav/deckcraft#3]
Hello as the title said, is it possible to update the modpack to 1.20.4. 

If it's some time issue, I would love to contribute, but there is no guideline how to do it so...
Please let me know if you have to project/time to update to 1.20.4.

**Comment by Uranite** [comment]
The mods are just not updated to 1.20.4, not even Quilted Fabric API is updated to 1.20.4

**Comment by intergrav** [comment]
I'll make an update today or tomorrow and probably start maintaining the modpack again. I plan on switching DeckCraft to Fabric so I can update it to newer versions
