### ISSUE TITLE
Minecraft 1.21 ETA?

### ISSUE THREAD

**Issue by MonkeyInPrivate** [intergrav/deckcraft#4]

**Comment by ghost** [comment]
when it's done

**Comment by sakecode** [comment]
never

**Comment by 8ballpizza** [comment]
never

**Comment by SympathyTea** [comment]
no + tophat
![your pfp with a shitty pixel art tophat](https://github.com/skywardmc/deckcraft/assets/116274772/66479232-ec0d-42eb-bb28-31f82b57c34e)

**Comment by uku3lig** [comment]
breaking: an unknown person just made a github issue

![a](https://i.ibb.co/3MdyjcJ/1916.jpg)

**Comment by intergrav** [comment]
Please do not ask for an ETA. It will be done when it's ready and when I have time to do so. I am very busy at the moment.
